[theme]
base = "dark"
primaryColor = "#1abc9c"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "monospace"


#[theme]
#primaryColor = "#667eea"
#backgroundColor = "#ffffff"
#secondaryBackgroundColor = "#f0f2f6"
#textColor = "#262730"
#font = "sans serif"

codeBackgroundColor = "#f5f5f5"

[server]
headless = true
# port = 8501 ← comment this out or remove for cloud platforms, Some platforms (like Streamlit Cloud) auto-assign ports. 
#To support that, omit the port setting unless you're running it locally.
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

